### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by xrviv** [EthereumPhone/WalletManager#3]
1. Has the project shifted focus from an Ethereum Phone to simply an Ethereum OS?
2. Will it have support for BTC? 

Thank you. Asking for walletscrutiny.com

**Comment by markusbug** [comment]
@xrviv 1. We focus on being an OS atm, but a hardware device is not out of the question 😄 .
2. For now just ethereum and EVM based chains 👍

**Comment by xrviv** [comment]
Thank you for the response! Alright, we filed it under "hardware" devices for now. Good luck!

**Comment by markusbug** [comment]
Thank you @xrviv.
